const mongoose = require("mongoose");

const depositSchema = new mongoose.Schema(
  {
    /*
    =================================================
    USER
    =================================================
    */

    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /*
    =================================================
    WALLET
    =================================================
    */

    wallet: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Wallet",
      required: true,
      index: true,
    },

    /*
    =================================================
    PAYMENT PROVIDER
    =================================================

    Examples:

    paystack
    flutterwave
    stripe
    */

    provider: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      index: true,
    },

    /*
    =================================================
    INTERNAL DEPOSIT REFERENCE
    =================================================

    This is generated by our system.

    Example:

    DEP-68D2A9...
    */

    reference: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true,
    },

    /*
    =================================================
    PROVIDER TRANSACTION ID
    =================================================

    This is supplied by the payment provider.

    It becomes extremely important for duplicate
    webhook protection.
    */

    providerTransactionId: {
      type: String,
      trim: true,
      default: null,
    },

    /*
    =================================================
    PAYMENT REFERENCE
    =================================================

    Some providers use a separate payment reference.
    */

    providerReference: {
      type: String,
      trim: true,
      default: null,
    },

    /*
    =================================================
    AMOUNT
    =================================================
    */

    amount: {
      type: mongoose.Schema.Types.Decimal128,
      required: true,
    },

    /*
    =================================================
    CURRENCY
    =================================================
    */

    currency: {
      type: String,
      enum: ["USD", "NGN", "CAD", "EUR"],
      required: true,
      uppercase: true,
    },

    /*
    =================================================
    STATUS
    =================================================
    */

    status: {
      type: String,
      enum: [
        "pending",
        "processing",
        "successful",
        "failed",
        "cancelled",
        "expired",
      ],
      default: "pending",
      index: true,
    },

    /*
    =================================================
    PAYMENT INITIALIZATION
    =================================================
    */

    paymentUrl: {
      type: String,
      default: null,
    },

    /*
    =================================================
    PROVIDER RESPONSE
    =================================================

    Keep this carefully controlled.

    Never store secrets, API keys, signatures,
    or sensitive authentication credentials.
    */

    providerData: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    /*
    =================================================
    VERIFICATION
    =================================================
    */

    verifiedAt: {
      type: Date,
      default: null,
    },

    verificationMethod: {
      type: String,
      enum: [
        "webhook",
        "server_verification",
        null,
      ],
      default: null,
    },

    /*
    =================================================
    WALLET CREDIT
    =================================================
    */

    creditedAt: {
      type: Date,
      default: null,
    },

    ledgerEntry: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LedgerEntry",
      default: null,
    },

    /*
    =================================================
    FAILURE INFORMATION
    =================================================
    */

    failureReason: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: null,
    },

    /*
    =================================================
    TIMESTAMPS
    =================================================
    */

    expiresAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

/*
=====================================================
DUPLICATE PROVIDER TRANSACTION PROTECTION
=====================================================

The same provider transaction must not be attached
to multiple deposits for the same provider.

Because providerTransactionId can initially be null,
we use a partial index.
=====================================================
*/

depositSchema.index(
  {
    provider: 1,
    providerTransactionId: 1,
  },
  {
    unique: true,
    partialFilterExpression: {
      providerTransactionId: {
        $type: "string",
      },
    },
  }
);

/*
=====================================================
USER DEPOSIT HISTORY
=====================================================
*/

depositSchema.index({
  user: 1,
  createdAt: -1,
});

/*
=====================================================
STATUS + DATE
=====================================================
*/

depositSchema.index({
  status: 1,
  createdAt: -1,
});

/*
=====================================================
WALLET + DATE
=====================================================
*/

depositSchema.index({
  wallet: 1,
  createdAt: -1,
});

module.exports = mongoose.model(
  "Deposit",
  depositSchema
);