const mongoose = require("mongoose");

const depositSchema = new mongoose.Schema(
  {
    /*
    =================================================
    USER
    =================================================
    */

    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /*
    =================================================
    USER WALLET
    =================================================

    The wallet that will receive the approved deposit.
    */

    wallet: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Wallet",
      required: true,
      index: true,
    },

    /*
    =================================================
    PAYMENT METHOD
    =================================================

    This references the payment method created by
    the administrator.

    Example:

    - USD Bank Account
    - NGN Bank Transfer
    - USDT TRC20
    - USDT ERC20
    */

    paymentMethod: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PaymentMethod",
      required: true,
      index: true,
    },

    /*
    =================================================
    PAYMENT TYPE
    =================================================

    Stored separately so the deposit history remains
    understandable even if the payment method is
    changed or deactivated later.
    */

    paymentType: {
      type: String,
      enum: ["bank_transfer", "crypto", "mobile_money", "other"],
      required: true,
      lowercase: true,
      trim: true,
      index: true,
    },

    /*
    =================================================
    INTERNAL DEPOSIT REFERENCE
    =================================================

    Generated by our own system.

    Example:

    DEP-68D2A9ABC123
    */

    reference: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true,
    },

    /*
    =================================================
    PAYMENT TRANSACTION REFERENCE
    =================================================

    This is entered by the user when available.

    Examples:

    Bank transfer reference
    Crypto transaction hash
    Transaction ID
    Deposit reference from another platform
    */

    transactionReference: {
      type: String,
      trim: true,
      default: null,
      maxlength: 200,
    },

    /*
    =================================================
    PAYMENT ASSET
    =================================================

    This is useful when the payment asset differs
    from the wallet currency.

    Example:

    Wallet currency: USD
    Payment asset: USDT

    Or:

    Wallet currency: NGN
    Payment asset: NGN
    */

    paymentAsset: {
      type: String,
      trim: true,
      uppercase: true,
      default: null,
      maxlength: 50,
    },

    /*
    =================================================
    PAYMENT NETWORK
    =================================================

    Mainly useful for cryptocurrency payments.

    Examples:

    TRC20
    ERC20
    BEP20

    Bank transfers can leave this as null.
    */

    paymentNetwork: {
      type: String,
      trim: true,
      default: null,
      maxlength: 100,
    },

    /*
    =================================================
    AMOUNT
    =================================================
    */

    amount: {
      type: mongoose.Schema.Types.Decimal128,
      required: true,
    },

    /*
    =================================================
    WALLET CURRENCY
    =================================================

    This is the currency that will be credited to
    the user's wallet after admin approval.

    Example:

    paymentAsset = USDT
    currency = USD

    The user's USD wallet receives the approved amount.
    */

    currency: {
      type: String,
      enum: ["USD", "NGN", "CAD", "EUR"],
      required: true,
      uppercase: true,
      trim: true,
      index: true,
    },

    /*
    =================================================
    PAYMENT PROOF
    =================================================

    User can upload proof of payment.

    We store the file URL/path rather than the actual
    file inside MongoDB.
    */

    paymentProof: {
      url: {
        type: String,
        trim: true,
        default: null,
      },

      publicId: {
        type: String,
        trim: true,
        default: null,
      },

      fileName: {
        type: String,
        trim: true,
        default: null,
      },

      mimeType: {
        type: String,
        trim: true,
        default: null,
      },

      uploadedAt: {
        type: Date,
        default: null,
      },
    },

    /*
    =================================================
    USER PAYMENT NOTE
    =================================================

    Optional message supplied by the user.

    Example:

    "I transferred the money from my GTBank account."
    */

    userNote: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: null,
    },

    /*
    =================================================
    STATUS
    =================================================

    pending:
      Deposit created but user has not confirmed
      payment yet.

    submitted:
      User clicked "I Have Made The Payment".

    under_review:
      Admin has started reviewing the payment.

    successful:
      Admin approved the payment and wallet was
      successfully credited.

    rejected:
      Admin rejected the payment.

    cancelled:
      Deposit was cancelled.

    expired:
      Deposit request expired.
    */

    status: {
      type: String,
      enum: [
        "pending",
        "submitted",
        "under_review",
        "processing",
        "successful",
        "rejected",
        "cancelled",
        "expired",
      ],
      default: "pending",
      index: true,
    },

    /*
    =================================================
    USER PAYMENT CONFIRMATION
    =================================================
    */

    paymentSubmittedAt: {
      type: Date,
      default: null,
      index: true,
    },

    /*
    =================================================
    ADMIN REVIEW
    =================================================

    Records which administrator reviewed the deposit.
    */

    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    reviewedAt: {
      type: Date,
      default: null,
    },

    /*
    =================================================
    ADMIN APPROVAL
    =================================================

    These fields are populated only when the admin
    approves the deposit.
    */

    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    approvedAt: {
      type: Date,
      default: null,
    },

    /*
    =================================================
    ADMIN REJECTION
    =================================================
    */

    rejectedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    rejectedAt: {
      type: Date,
      default: null,
    },

    rejectionReason: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: null,
    },

    /*
    =================================================
    ADMIN NOTE
    =================================================

    Internal note that administrators can leave
    about the payment.
    */

    adminNote: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: null,
    },

    /*
    =================================================
    WALLET CREDIT
    =================================================

    These fields prove that the approved deposit
    actually resulted in a wallet credit.

    This is important for preventing duplicate credits.
    */

    creditedAt: {
      type: Date,
      default: null,
    },

    /*
    =================================================
    LEDGER ENTRY
    =================================================

    References the ledger entry created when the
    deposit is approved.
    */

    ledgerEntry: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LedgerEntry",
      default: null,
      index: true,
    },

    /*
    =================================================
    CREDIT PROCESSING KEY
    =================================================

    Internal idempotency protection.

    A successful deposit should only be credited
    once, even if an admin accidentally sends the
    approval request twice.
    */

    creditReference: {
      type: String,
      trim: true,
      default: null,
    },

    /*
    =================================================
    FAILURE / ERROR INFORMATION
    =================================================

    Used for internal processing errors rather than
    normal admin rejection.

    Example:

    "Unable to create ledger entry."
    */

    failureReason: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: null,
    },

    /*
    =================================================
    EXPIRATION
    =================================================

    Optional expiration date for a deposit request.

    Example:

    User creates a deposit request today and has
    24 hours to complete it.
    */

    expiresAt: {
      type: Date,
      default: null,
      index: true,
    },
  },
  {
    timestamps: true,
  },
);

/*
=====================================================
USER DEPOSIT HISTORY
=====================================================
*/

depositSchema.index({
  user: 1,
  createdAt: -1,
});

/*
=====================================================
ADMIN DEPOSIT MANAGEMENT
=====================================================
*/

depositSchema.index({
  status: 1,
  createdAt: -1,
});

/*
=====================================================
WALLET DEPOSIT HISTORY
=====================================================
*/

depositSchema.index({
  wallet: 1,
  createdAt: -1,
});

/*
=====================================================
PAYMENT METHOD HISTORY
=====================================================
*/

depositSchema.index({
  paymentMethod: 1,
  createdAt: -1,
});

/*
=====================================================
CURRENCY + STATUS
=====================================================
*/

depositSchema.index({
  currency: 1,
  status: 1,
  createdAt: -1,
});

/*
=====================================================
ADMIN REVIEW HISTORY
=====================================================
*/

depositSchema.index({
  reviewedBy: 1,
  reviewedAt: -1,
});

/*
=====================================================
APPROVAL HISTORY
=====================================================
*/

depositSchema.index({
  approvedBy: 1,
  approvedAt: -1,
});

/*
=====================================================
MODEL
=====================================================
*/

module.exports = mongoose.model("Deposit", depositSchema);
